// packages/angular/stories/playground.ts
import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import {
  CoAppShell,
  CoBanner,
  CoButton,
  CoButtonIcon,
  CoCard,
  CoCheckbox,
  CoCheckboxGroup,
  CoCheckboxIndeterminate,
  CoCombobox,
  CoForm,
  CoIcon,
  CoInput,
  CoInputPill,
  CoLabel,
  CoListbox,
  CoNavDrawer,
  CoNavDrawerItem,
  CoNavHeaderBar,
  CoNavRailBar,
  CoNavRailItem,
  CoNavSeparator,
  CoOption,
  CoRadio,
  CoRadioGroup,
  CoSelect,
  CoTextarea,
} from '@cobalt/angular';
import {
  getWrapperStoryArgs,
  getWrapperStoryArgTypes,
  getWrapperStoryEventProps,
  getWrapperStoryOptionItems,
  getWrapperStoryScenarioArgs,
  getWrapperStorySelectedValues,
  type WrapperStoryArgs,
  type WrapperStoryComponentId,
} from '@cobalt/storybook-fixtures';

const moduleMetadata = {
  imports: [
    CoAppShell,
    CoBanner,
    CoButton,
    CoButtonIcon,
    CoCard,
    CoCheckbox,
    CoCheckboxGroup,
    CoCheckboxIndeterminate,
    CoCombobox,
    CoForm,
    CoIcon,
    CoInput,
    CoInputPill,
    CoLabel,
    CoListbox,
    CoNavDrawer,
    CoNavDrawerItem,
    CoNavHeaderBar,
    CoNavRailBar,
    CoNavRailItem,
    CoNavSeparator,
    CoOption,
    CoRadio,
    CoRadioGroup,
    CoSelect,
    CoTextarea,
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
};

export function createAngularPlaygroundStory(componentId: WrapperStoryComponentId) {
  return {
    args: getWrapperStoryArgs(componentId),
    argTypes: getWrapperStoryArgTypes(componentId),
    parameters: {
      cobaltSource: {
        componentId,
      },
    },
    render: (args: WrapperStoryArgs) => renderAngularPlayground(componentId, args),
  };
}

export function createAngularScenarioStory(
  componentId: WrapperStoryComponentId,
  scenarioId: string,
) {
  return {
    args: getWrapperStoryScenarioArgs(componentId, scenarioId),
    parameters: {
      controls: { disable: true },
      cobaltSource: {
        componentId,
        scenarioId,
      },
    },
    render: (args: WrapperStoryArgs) => renderAngularPlayground(componentId, args),
  };
}

export function renderAngularPlayground(
  componentId: WrapperStoryComponentId,
  args: WrapperStoryArgs,
) {
  return {
    moduleMetadata,
    props: {
      ...args,
      ...getWrapperStoryEventProps(componentId, args),
      optionItems: getWrapperStoryOptionItems(componentId, args),
      selectedValues: getWrapperStorySelectedValues(args),
    },
    template: getTemplate(componentId),
  };
}

function getTemplate(componentId: WrapperStoryComponentId): string {
  switch (componentId) {
    case 'appShell':
      return frame(
        'cobalt-grid',
        `
          <co-app-shell
            style="block-size: 620px;"
            [drawerOpen]="drawerOpen"
            [railWidth]="railWidth"
            [drawerWidth]="drawerWidth"
            (coDrawerOpen)="onCoDrawerOpen($event)"
            (coDrawerClose)="onCoDrawerClose($event)"
            (coDrawerToggle)="onCoDrawerToggle($event)"
          >
            <co-banner slot="banner">
              @if (slotBanner) {
                <span slot="title">{{ slotBanner }}</span>
              }
              Previewing the responsive application frame.
            </co-banner>
            <co-nav-header-bar slot="topnav" label="Application header">
              @if (slotTopnav) {
                <span slot="logo">{{ slotTopnav }}</span>
              }
              <co-input-pill variant="search" placeholder="Search"></co-input-pill>
            </co-nav-header-bar>
            <co-nav-rail-bar slot="rail" [value]="selectedValues[0]" label="Primary navigation">
              @for (item of optionItems; track item.value) {
                <co-nav-rail-item
                  [value]="item.value"
                  [icon]="item.icon || 'home'"
                  [selected]="selectedValues.includes(item.value)"
                  [disabled]="item.disabled"
                >
                  {{ item.label }}
                </co-nav-rail-item>
              }
            </co-nav-rail-bar>
            <co-nav-drawer slot="drawer" [value]="selectedValues[0]" label="Primary navigation">
              @for (item of optionItems; track item.value) {
                <co-nav-drawer-item
                  [value]="item.value"
                  [icon]="item.icon || 'home'"
                  [selected]="selectedValues.includes(item.value)"
                  [disabled]="item.disabled"
                >
                  {{ item.label }}
                </co-nav-drawer-item>
              }
              <co-nav-separator></co-nav-separator>
              <co-nav-drawer-item value="help" icon="info">Help</co-nav-drawer-item>
            </co-nav-drawer>
            <co-card slot="body" label="Dashboard content">
              @if (slotBody) {
                <span slot="header">{{ slotBody }}</span>
              }
              <div class="cobalt-stack">
                Use the shell to compose persistent navigation, responsive drawer behavior, and page content.
              </div>
            </co-card>
            @if (slotFooter) {
              <span slot="footer">{{ slotFooter }}</span>
            }
          </co-app-shell>
        `,
      );
    case 'banner':
      return frame(
        'cobalt-grid',
        `
          <co-banner [label]="label">
            @if (slotTitle) {
              <span slot="title">{{ slotTitle }}</span>
            }
            {{ slotDefault }}
          </co-banner>
        `,
      );
    case 'button':
      return frame(
        'cobalt-row',
        `
          <co-button
            [variant]="variant"
            [size]="size"
            [disabled]="disabled"
            [loading]="loading"
            [type]="type"
            [href]="href"
            [target]="target"
            (coFocus)="onCoFocus($event)"
            (coBlur)="onCoBlur($event)"
          >
            @if (slotPrefix) {
              <co-icon slot="prefix" [name]="slotPrefix" size="sm"></co-icon>
            }
            {{ slotDefault }}
            @if (slotSuffix) {
              <co-icon slot="suffix" [name]="slotSuffix" size="sm"></co-icon>
            }
          </co-button>
        `,
      );
    case 'buttonIcon':
      return frame(
        'cobalt-grid',
        `
          <co-button-icon
            [name]="name"
            [variant]="variant"
            [size]="size"
            [label]="label"
            [labelPosition]="labelPosition"
            [circle]="circle"
            [disabled]="disabled"
            (coFocus)="onCoFocus($event)"
            (coBlur)="onCoBlur($event)"
          ></co-button-icon>
        `,
      );
    case 'card':
      return frame(
        'cobalt-grid',
        `
          <co-card class="cobalt-panel" [label]="label">
            @if (slotHeader) {
              <span slot="header">{{ slotHeader }}</span>
            }
            {{ slotDefault }}
            @if (slotFooter) {
              <span slot="footer">{{ slotFooter }}</span>
            }
          </co-card>
        `,
      );
    case 'checkbox':
      return frame(
        'cobalt-grid',
        `
          <co-checkbox [value]="value" [checked]="checked" [disabled]="disabled">
            {{ slotDefault }}
          </co-checkbox>
        `,
      );
    case 'checkboxGroup':
      return frame(
        'cobalt-grid',
        `
          <co-checkbox-group
            [name]="name"
            [disabled]="disabled"
            [required]="required"
            (coChange)="onCoChange($event)"
          >
            @if (slotLabel) {
              <span slot="label">{{ slotLabel }}</span>
            }
            @if (slotHelpText) {
              <span slot="help-text">{{ slotHelpText }}</span>
            }
            @if (slotFeedback) {
              <span slot="feedback">{{ slotFeedback }}</span>
            }
            @for (item of optionItems; track item.value) {
              <co-checkbox
                [value]="item.value"
                [checked]="selectedValues.includes(item.value)"
                [disabled]="item.disabled"
              >
                {{ item.label }}
              </co-checkbox>
            }
          </co-checkbox-group>
        `,
      );
    case 'checkboxIndeterminate':
      return frame(
        'cobalt-grid',
        `
          <co-checkbox-indeterminate
            [value]="value"
            [checked]="checked"
            [indeterminate]="indeterminate"
            [mixedState]="mixedState"
            [disabled]="disabled"
          >
            @if (slotLabel) {
              <span slot="label">{{ slotLabel }}</span>
            }
            @for (item of optionItems; track item.value) {
              <co-checkbox
                [value]="item.value"
                [checked]="selectedValues.includes(item.value)"
                [disabled]="item.disabled"
              >
                {{ item.label }}
              </co-checkbox>
            }
          </co-checkbox-indeterminate>
        `,
      );
    case 'icon':
      return frame(
        'cobalt-row',
        `
          <co-icon
            [name]="name"
            [size]="size"
            [fill]="fill"
            [animated]="animated"
            [label]="label"
          ></co-icon>
        `,
      );
    case 'input':
      return frame(
        'cobalt-grid',
        `
          <co-input
            [size]="size"
            [danger]="danger"
            [disabled]="disabled"
            [readOnly]="readOnly"
            [required]="required"
            [label]="label"
            [helpText]="helpText"
            [name]="name"
            [type]="type"
            [placeholder]="placeholder"
            [value]="value"
            [modelValue]="modelValue"
            (coFocus)="onCoFocus($event)"
            (coBlur)="onCoBlur($event)"
            (coInput)="onCoInput($event)"
            (coChange)="onCoChange($event)"
          >
            @if (slotPrefix) {
              <co-icon slot="prefix" [name]="slotPrefix" size="sm"></co-icon>
            }
            @if (slotSuffix) {
              <co-icon slot="suffix" [name]="slotSuffix" size="sm"></co-icon>
            }
            @if (slotFeedback) {
              <span slot="feedback">{{ slotFeedback }}</span>
            }
          </co-input>
        `,
      );
    case 'inputPill':
      return frame(
        'cobalt-grid',
        `
          <co-input-pill
            [variant]="variant"
            [actionIcon]="actionIcon"
            [prefixIcon]="prefixIcon"
            [size]="size"
            [disabled]="disabled"
            [name]="name"
            [type]="type"
            [placeholder]="placeholder"
            [value]="value"
            [modelValue]="modelValue"
            (coAction)="onCoAction($event)"
            (coFocus)="onCoFocus($event)"
            (coBlur)="onCoBlur($event)"
          >
            @if (slotPrefix) {
              <co-icon slot="prefix" [name]="slotPrefix" size="sm"></co-icon>
            }
            @if (slotSuffix) {
              <co-icon slot="suffix" [name]="slotSuffix" size="sm"></co-icon>
            }
          </co-input-pill>
        `,
      );
    case 'label':
      return frame(
        'cobalt-grid',
        `
          <co-label
            [htmlFor]="htmlFor"
            [required]="required"
            [optional]="optional"
            [optionalLabel]="optionalLabel"
          >
            @if (slotPrefix) {
              <co-icon slot="prefix" [name]="slotPrefix" size="sm"></co-icon>
            }
            {{ slotDefault }}
            @if (slotSuffix) {
              <co-icon slot="suffix" [name]="slotSuffix" size="sm"></co-icon>
            }
          </co-label>
        `,
      );
    case 'textarea':
      return frame(
        'cobalt-grid',
        `
          <co-textarea
            [size]="size"
            [resize]="resize"
            [danger]="danger"
            [disabled]="disabled"
            [readOnly]="readOnly"
            [required]="required"
            [label]="label"
            [helpText]="helpText"
            [name]="name"
            [placeholder]="placeholder"
            [value]="value"
            [modelValue]="modelValue"
            [rows]="rows"
            [maxRows]="maxRows"
            [maxLength]="maxLength"
            [minLength]="minLength"
            (coFocus)="onCoFocus($event)"
            (coBlur)="onCoBlur($event)"
            (coInput)="onCoInput($event)"
            (coChange)="onCoChange($event)"
          >
            @if (slotPrefix) {
              <co-icon slot="prefix" [name]="slotPrefix" size="sm"></co-icon>
            }
            @if (slotSuffix) {
              <co-icon slot="suffix" [name]="slotSuffix" size="sm"></co-icon>
            }
            @if (slotFeedback) {
              <span slot="feedback">{{ slotFeedback }}</span>
            }
          </co-textarea>
        `,
      );
    case 'option':
      return frame(
        'cobalt-grid',
        `
          <co-listbox label="Option preview" name="option-preview">
            <co-option
              [value]="value"
              [choiceValue]="choiceValue"
              [checked]="checked"
              [disabled]="disabled"
              [active]="active"
            >
              @if (slotIndicatorIcon) {
                <co-icon slot="indicator-icon" [name]="slotIndicatorIcon" size="sm"></co-icon>
              }
              @if (slotIndicator) {
                <span slot="indicator">{{ slotIndicator }}</span>
              }
              {{ slotDefault }}
            </co-option>
          </co-listbox>
        `,
      );
    case 'navDrawer':
      return frame(
        'cobalt-grid',
        `
          <co-nav-drawer
            [open]="open"
            [value]="value"
            [label]="label"
            (coChange)="onCoChange($event)"
          >
            @for (item of optionItems; track item.value) {
              <co-nav-drawer-item
                [value]="item.value"
                [icon]="item.icon || 'home'"
                [selected]="selectedValues.includes(item.value)"
                [disabled]="item.disabled"
              >
                {{ item.label }}
              </co-nav-drawer-item>
            }
            <co-nav-separator></co-nav-separator>
            <co-nav-drawer-item value="help" icon="info">Help</co-nav-drawer-item>
          </co-nav-drawer>
        `,
      );
    case 'navDrawerItem':
      return frame(
        'cobalt-grid',
        `
          <co-nav-drawer label="Drawer item preview">
            <co-nav-drawer-item
              [value]="value"
              [icon]="icon"
              [href]="href"
              [selected]="selected"
              [disabled]="disabled"
            >
              @if (slotPrefix) {
                <co-icon slot="prefix" [name]="slotPrefix" size="sm"></co-icon>
              }
              {{ slotDefault }}
            </co-nav-drawer-item>
          </co-nav-drawer>
        `,
      );
    case 'navHeaderBar':
      return frame(
        'cobalt-grid',
        `
          <co-nav-header-bar [label]="label">
            @if (slotLogo) {
              <span slot="logo">{{ slotLogo }}</span>
            }
            <div class="cobalt-form-row">
              <co-button variant="ghost" size="sm">Overview</co-button>
              <co-button variant="ghost" size="sm">Reports</co-button>
              <co-button variant="ghost" size="sm">Settings</co-button>
            </div>
            @if (slotAvatar) {
              <span slot="avatar">{{ slotAvatar }}</span>
            }
          </co-nav-header-bar>
        `,
      );
    case 'navRailBar':
      return frame(
        'cobalt-grid',
        `
          <co-nav-rail-bar [value]="value" [label]="label" (coChange)="onCoChange($event)">
            @for (item of optionItems; track item.value) {
              <co-nav-rail-item
                [value]="item.value"
                [icon]="item.icon || 'home'"
                [selected]="selectedValues.includes(item.value)"
                [disabled]="item.disabled"
              >
                {{ item.label }}
              </co-nav-rail-item>
            }
          </co-nav-rail-bar>
        `,
      );
    case 'navRailItem':
      return frame(
        'cobalt-grid',
        `
          <co-nav-rail-bar label="Rail item preview">
            <co-nav-rail-item
              [value]="value"
              [icon]="icon"
              [href]="href"
              [target]="target"
              [label]="label"
              [selected]="selected"
              [disabled]="disabled"
            >
              @if (slotIcon) {
                <co-icon slot="icon" [name]="slotIcon" size="sm"></co-icon>
              }
              {{ slotDefault }}
            </co-nav-rail-item>
          </co-nav-rail-bar>
        `,
      );
    case 'navSeparator':
      return frame(
        'cobalt-grid',
        `
          <co-nav-drawer label="Separator preview">
            <co-nav-drawer-item value="overview" icon="home" [selected]="true">Overview</co-nav-drawer-item>
            <co-nav-separator></co-nav-separator>
            <co-nav-drawer-item value="settings" icon="settings">Settings</co-nav-drawer-item>
          </co-nav-drawer>
        `,
      );
    case 'radio':
      return frame(
        'cobalt-grid',
        `
          <co-radio [value]="value" [checked]="checked" [disabled]="disabled">
            {{ slotDefault }}
          </co-radio>
        `,
      );
    case 'radioGroup':
      return frame(
        'cobalt-grid',
        `
          <co-radio-group
            [name]="name"
            [disabled]="disabled"
            [required]="required"
            (coChange)="onCoChange($event)"
          >
            @if (slotLabel) {
              <span slot="label">{{ slotLabel }}</span>
            }
            @if (slotHelpText) {
              <span slot="help-text">{{ slotHelpText }}</span>
            }
            @if (slotFeedback) {
              <span slot="feedback">{{ slotFeedback }}</span>
            }
            @for (item of optionItems; track item.value) {
              <co-radio
                [value]="item.value"
                [checked]="selectedValues.includes(item.value)"
                [disabled]="item.disabled"
              >
                {{ item.label }}
              </co-radio>
            }
          </co-radio-group>
        `,
      );
    case 'listbox':
      return frame(
        'cobalt-grid',
        `
          <co-listbox
            [label]="label"
            [helpText]="helpText"
            [name]="name"
            [disabled]="disabled"
            [required]="required"
            [multipleChoice]="multipleChoice"
            [orientation]="orientation"
            [selectionFollowsFocus]="selectionFollowsFocus"
            [rotateKeyboardNavigation]="rotateKeyboardNavigation"
            [hasNoDefaultSelected]="hasNoDefaultSelected"
            [modelValue]="modelValue"
            (coChange)="onCoChange($event)"
          >
            @if (slotFeedback) {
              <span slot="feedback">{{ slotFeedback }}</span>
            }
            @for (item of optionItems; track item.value) {
              <co-option
                [value]="item.value"
                [checked]="selectedValues.includes(item.value)"
                [disabled]="item.disabled"
              >
                {{ item.label }}
              </co-option>
            }
          </co-listbox>
        `,
      );
    case 'combobox':
      return frame(
        'cobalt-grid',
        `
          <co-combobox
            [size]="size"
            [danger]="danger"
            [disabled]="disabled"
            [readOnly]="readOnly"
            [required]="required"
            [label]="label"
            [helpText]="helpText"
            [name]="name"
            [value]="value"
            [modelValue]="modelValue"
            [autocomplete]="autocomplete"
            [matchMode]="matchMode"
            [showAllOnEmpty]="showAllOnEmpty"
            [selectionFollowsFocus]="selectionFollowsFocus"
            [rotateKeyboardNavigation]="rotateKeyboardNavigation"
            [hasNoDefaultSelected]="hasNoDefaultSelected"
            [multiple]="multiple"
            [multipleChoice]="multipleChoice"
            [allowCustomChoice]="allowCustomChoice"
            [matchError]="matchError"
            [requireOptionMatch]="requireOptionMatch"
            (coFocus)="onCoFocus($event)"
            (coBlur)="onCoBlur($event)"
            (coInput)="onCoInput($event)"
            (coChange)="onCoChange($event)"
          >
            @if (slotPrefix) {
              <co-icon slot="prefix" [name]="slotPrefix" size="sm"></co-icon>
            }
            @if (slotSuffix) {
              <co-icon slot="suffix" [name]="slotSuffix" size="sm"></co-icon>
            }
            @if (slotFeedback) {
              <span slot="feedback">{{ slotFeedback }}</span>
            }
            @for (item of optionItems; track item.value) {
              <co-option
                [value]="item.value"
                [checked]="selectedValues.includes(item.value)"
                [disabled]="item.disabled"
              >
                {{ item.label }}
              </co-option>
            }
          </co-combobox>
        `,
      );
    case 'select':
      return frame(
        'cobalt-grid',
        `
          <co-select
            [size]="size"
            [danger]="danger"
            [disabled]="disabled"
            [readOnly]="readOnly"
            [required]="required"
            [hasNoDefaultSelected]="hasNoDefaultSelected"
            (coFocus)="onCoFocus($event)"
            (coBlur)="onCoBlur($event)"
            (coChange)="onCoChange($event)"
          >
            @if (slotLabel) {
              <span slot="label">{{ slotLabel }}</span>
            }
            @if (slotHelpText) {
              <span slot="help-text">{{ slotHelpText }}</span>
            }
            @if (slotFeedback) {
              <span slot="feedback">{{ slotFeedback }}</span>
            }
            @for (item of optionItems; track item.value) {
              <co-option
                [value]="item.value"
                [checked]="selectedValues.includes(item.value)"
                [disabled]="item.disabled"
              >
                {{ item.label }}
              </co-option>
            }
          </co-select>
        `,
      );
    case 'form':
      return frame(
        'cobalt-grid',
        `
          <co-form
            class="cobalt-panel"
            [disabled]="disabled"
            [label]="label"
            [helpText]="helpText"
            [name]="name"
            (coSubmit)="onCoSubmit($event)"
            (coReset)="onCoReset($event)"
          >
            @if (slotFeedback) {
              <span slot="feedback">{{ slotFeedback }}</span>
            }
            <div class="cobalt-stack">
              <co-input label="Name" name="name" required placeholder="Ada Lovelace"></co-input>
              <co-textarea label="Message" name="message" [rows]="4" placeholder="Write a message">
              </co-textarea>
              <div class="cobalt-form-row">
                <co-button type="submit" variant="primary">Submit</co-button>
                <co-button type="reset" variant="secondary">Reset</co-button>
              </div>
            </div>
          </co-form>
        `,
      );
  }
}

function frame(layoutClass: string, content: string) {
  return `
    <div class="cobalt-story cobalt-stack">
      <section class="cobalt-section">
        <div class="${layoutClass}">
          ${content}
        </div>
      </section>
    </div>
  `;
}

// packages/react/stories/playground.tsx
import {
  CoAppShell,
  CoBanner,
  CoButton,
  CoButtonIcon,
  CoCard,
  CoCheckbox,
  CoCheckboxGroup,
  CoCheckboxIndeterminate,
  CoCombobox,
  CoForm,
  CoIcon,
  CoInput,
  CoInputPill,
  CoLabel,
  CoListbox,
  CoNavDrawer,
  CoNavDrawerItem,
  CoNavHeaderBar,
  CoNavRailBar,
  CoNavRailItem,
  CoNavSeparator,
  CoOption,
  CoRadio,
  CoRadioGroup,
  CoSelect,
  CoTextarea,
} from '@cobalt/react';
import {
  getWrapperStoryArgs,
  getWrapperStoryArgTypes,
  getWrapperStoryComponentProps,
  getWrapperStoryEventProps,
  getWrapperStoryOptionItems,
  getWrapperStoryScenarioArgs,
  getWrapperStorySelectedValues,
  getWrapperStorySlotValue,
  type WrapperStoryArgs,
  type WrapperStoryComponentId,
} from '@cobalt/storybook-fixtures';

export function createReactPlaygroundStory(componentId: WrapperStoryComponentId) {
  return {
    args: getWrapperStoryArgs(componentId),
    argTypes: getWrapperStoryArgTypes(componentId),
    parameters: {
      cobaltSource: {
        componentId,
      },
    },
    render: (args: WrapperStoryArgs) => renderReactPlayground(componentId, args),
  };
}

export function createReactScenarioStory(componentId: WrapperStoryComponentId, scenarioId: string) {
  return {
    args: getWrapperStoryScenarioArgs(componentId, scenarioId),
    parameters: {
      controls: { disable: true },
      cobaltSource: {
        componentId,
        scenarioId,
      },
    },
    render: (args: WrapperStoryArgs) => renderReactPlayground(componentId, args),
  };
}

export function renderReactPlayground(
  componentId: WrapperStoryComponentId,
  args: WrapperStoryArgs,
) {
  return (
    <div className="cobalt-story cobalt-stack">
      <section className="cobalt-section">
        <div
          className={
            componentId === 'button' || componentId === 'icon' ? 'cobalt-row' : 'cobalt-grid'
          }
        >
          {renderComponent(componentId, args)}
        </div>
      </section>
    </div>
  );
}

function renderComponent(componentId: WrapperStoryComponentId, args: WrapperStoryArgs) {
  switch (componentId) {
    case 'appShell':
      return (
        <CoAppShell
          style={{ blockSize: '620px' }}
          {...getWrapperStoryComponentProps('appShell', args)}
          {...getWrapperStoryEventProps('appShell', args)}
        >
          <CoBanner slot="banner">
            {slotText('title', getWrapperStorySlotValue('appShell', 'banner', args))}
            Previewing the responsive application frame.
          </CoBanner>
          <CoNavHeaderBar slot="topnav" label="Application header">
            {slotText('logo', getWrapperStorySlotValue('appShell', 'topnav', args))}
            <CoInputPill variant="search" placeholder="Search" />
          </CoNavHeaderBar>
          {railBar('rail', args)}
          {drawer('drawer', args)}
          <CoCard slot="body" label="Dashboard content">
            {slotText('header', getWrapperStorySlotValue('appShell', 'body', args))}
            <div className="cobalt-stack">
              Use the shell to compose persistent navigation, responsive drawer behavior, and page
              content.
            </div>
          </CoCard>
          {slotText('footer', getWrapperStorySlotValue('appShell', 'footer', args))}
        </CoAppShell>
      );
    case 'banner':
      return (
        <CoBanner {...getWrapperStoryComponentProps('banner', args)}>
          {slotText('title', getWrapperStorySlotValue('banner', 'title', args))}
          {getWrapperStorySlotValue('banner', '', args)}
        </CoBanner>
      );
    case 'button':
      return (
        <CoButton
          {...getWrapperStoryComponentProps('button', args)}
          {...getWrapperStoryEventProps('button', args)}
        >
          {slotIcon('prefix', getWrapperStorySlotValue('button', 'prefix', args))}
          {getWrapperStorySlotValue('button', '', args)}
          {slotIcon('suffix', getWrapperStorySlotValue('button', 'suffix', args))}
        </CoButton>
      );
    case 'buttonIcon':
      return (
        <CoButtonIcon
          {...getWrapperStoryComponentProps('buttonIcon', args)}
          {...getWrapperStoryEventProps('buttonIcon', args)}
        />
      );
    case 'card':
      return (
        <CoCard className="cobalt-panel" {...getWrapperStoryComponentProps('card', args)}>
          {slotText('header', getWrapperStorySlotValue('card', 'header', args))}
          {getWrapperStorySlotValue('card', '', args)}
          {slotText('footer', getWrapperStorySlotValue('card', 'footer', args))}
        </CoCard>
      );
    case 'checkbox':
      return (
        <CoCheckbox {...getWrapperStoryComponentProps('checkbox', args)}>
          {getWrapperStorySlotValue('checkbox', '', args)}
        </CoCheckbox>
      );
    case 'checkboxGroup':
      return (
        <CoCheckboxGroup
          {...getWrapperStoryComponentProps('checkboxGroup', args)}
          {...getWrapperStoryEventProps('checkboxGroup', args)}
        >
          {slotText('label', getWrapperStorySlotValue('checkboxGroup', 'label', args))}
          {slotText('help-text', getWrapperStorySlotValue('checkboxGroup', 'help-text', args))}
          {slotText('feedback', getWrapperStorySlotValue('checkboxGroup', 'feedback', args))}
          {checkboxChildren('checkboxGroup', args)}
        </CoCheckboxGroup>
      );
    case 'checkboxIndeterminate':
      return (
        <CoCheckboxIndeterminate {...getWrapperStoryComponentProps('checkboxIndeterminate', args)}>
          {slotText('label', getWrapperStorySlotValue('checkboxIndeterminate', 'label', args))}
          {checkboxChildren('checkboxIndeterminate', args)}
        </CoCheckboxIndeterminate>
      );
    case 'icon':
      return <CoIcon {...getWrapperStoryComponentProps('icon', args)} />;
    case 'input':
      return (
        <CoInput
          {...getWrapperStoryComponentProps('input', args)}
          {...getWrapperStoryEventProps('input', args)}
        >
          {slotIcon('prefix', getWrapperStorySlotValue('input', 'prefix', args))}
          {slotIcon('suffix', getWrapperStorySlotValue('input', 'suffix', args))}
          {slotText('feedback', getWrapperStorySlotValue('input', 'feedback', args))}
        </CoInput>
      );
    case 'inputPill':
      return (
        <CoInputPill
          {...getWrapperStoryComponentProps('inputPill', args)}
          {...getWrapperStoryEventProps('inputPill', args)}
        >
          {slotIcon('prefix', getWrapperStorySlotValue('inputPill', 'prefix', args))}
          {slotIcon('suffix', getWrapperStorySlotValue('inputPill', 'suffix', args))}
        </CoInputPill>
      );
    case 'label':
      return (
        <CoLabel {...getWrapperStoryComponentProps('label', args)}>
          {slotIcon('prefix', getWrapperStorySlotValue('label', 'prefix', args))}
          {getWrapperStorySlotValue('label', '', args)}
          {slotIcon('suffix', getWrapperStorySlotValue('label', 'suffix', args))}
        </CoLabel>
      );
    case 'textarea':
      return (
        <CoTextarea
          {...getWrapperStoryComponentProps('textarea', args)}
          {...getWrapperStoryEventProps('textarea', args)}
        >
          {slotIcon('prefix', getWrapperStorySlotValue('textarea', 'prefix', args))}
          {slotIcon('suffix', getWrapperStorySlotValue('textarea', 'suffix', args))}
          {slotText('feedback', getWrapperStorySlotValue('textarea', 'feedback', args))}
        </CoTextarea>
      );
    case 'option':
      return (
        <CoListbox label="Option preview" name="option-preview">
          <CoOption {...getWrapperStoryComponentProps('option', args)}>
            {slotIcon('indicator-icon', getWrapperStorySlotValue('option', 'indicator-icon', args))}
            {slotText('indicator', getWrapperStorySlotValue('option', 'indicator', args))}
            {getWrapperStorySlotValue('option', '', args)}
          </CoOption>
        </CoListbox>
      );
    case 'navDrawer':
      return drawer(undefined, args);
    case 'navDrawerItem':
      return (
        <CoNavDrawer label="Drawer item preview">
          <CoNavDrawerItem {...getWrapperStoryComponentProps('navDrawerItem', args)}>
            {slotIcon('prefix', getWrapperStorySlotValue('navDrawerItem', 'prefix', args))}
            {getWrapperStorySlotValue('navDrawerItem', '', args)}
          </CoNavDrawerItem>
        </CoNavDrawer>
      );
    case 'navHeaderBar':
      return (
        <CoNavHeaderBar {...getWrapperStoryComponentProps('navHeaderBar', args)}>
          {slotText('logo', getWrapperStorySlotValue('navHeaderBar', 'logo', args))}
          <div className="cobalt-form-row">
            <CoButton variant="ghost" size="sm">
              Overview
            </CoButton>
            <CoButton variant="ghost" size="sm">
              Reports
            </CoButton>
            <CoButton variant="ghost" size="sm">
              Settings
            </CoButton>
          </div>
          {slotText('avatar', getWrapperStorySlotValue('navHeaderBar', 'avatar', args))}
        </CoNavHeaderBar>
      );
    case 'navRailBar':
      return railBar(undefined, args);
    case 'navRailItem':
      return (
        <CoNavRailBar label="Rail item preview">
          <CoNavRailItem {...getWrapperStoryComponentProps('navRailItem', args)}>
            {slotIcon('icon', getWrapperStorySlotValue('navRailItem', 'icon', args))}
            {getWrapperStorySlotValue('navRailItem', '', args)}
          </CoNavRailItem>
        </CoNavRailBar>
      );
    case 'navSeparator':
      return (
        <CoNavDrawer label="Separator preview">
          <CoNavDrawerItem value="overview" icon="home" selected>
            Overview
          </CoNavDrawerItem>
          <CoNavSeparator />
          <CoNavDrawerItem value="settings" icon="settings">
            Settings
          </CoNavDrawerItem>
        </CoNavDrawer>
      );
    case 'radio':
      return (
        <CoRadio {...getWrapperStoryComponentProps('radio', args)}>
          {getWrapperStorySlotValue('radio', '', args)}
        </CoRadio>
      );
    case 'radioGroup':
      return (
        <CoRadioGroup
          {...getWrapperStoryComponentProps('radioGroup', args)}
          {...getWrapperStoryEventProps('radioGroup', args)}
        >
          {slotText('label', getWrapperStorySlotValue('radioGroup', 'label', args))}
          {slotText('help-text', getWrapperStorySlotValue('radioGroup', 'help-text', args))}
          {slotText('feedback', getWrapperStorySlotValue('radioGroup', 'feedback', args))}
          {radioChildren('radioGroup', args)}
        </CoRadioGroup>
      );
    case 'listbox':
      return (
        <CoListbox
          {...getWrapperStoryComponentProps('listbox', args)}
          {...getWrapperStoryEventProps('listbox', args)}
        >
          {slotText('feedback', getWrapperStorySlotValue('listbox', 'feedback', args))}
          {optionChildren('listbox', args)}
        </CoListbox>
      );
    case 'select':
      return (
        <CoSelect
          {...getWrapperStoryComponentProps('select', args)}
          {...getWrapperStoryEventProps('select', args)}
        >
          {slotText('label', getWrapperStorySlotValue('select', 'label', args))}
          {slotText('help-text', getWrapperStorySlotValue('select', 'help-text', args))}
          {slotText('feedback', getWrapperStorySlotValue('select', 'feedback', args))}
          {optionChildren('select', args)}
        </CoSelect>
      );
    case 'combobox':
      return (
        <CoCombobox
          {...getWrapperStoryComponentProps('combobox', args)}
          {...getWrapperStoryEventProps('combobox', args)}
        >
          {slotIcon('prefix', getWrapperStorySlotValue('combobox', 'prefix', args))}
          {slotIcon('suffix', getWrapperStorySlotValue('combobox', 'suffix', args))}
          {slotText('feedback', getWrapperStorySlotValue('combobox', 'feedback', args))}
          {optionChildren('combobox', args)}
        </CoCombobox>
      );
    case 'form':
      return (
        <CoForm
          className="cobalt-panel"
          {...getWrapperStoryComponentProps('form', args)}
          {...getWrapperStoryEventProps('form', args)}
        >
          {slotText('feedback', getWrapperStorySlotValue('form', 'feedback', args))}
          <div className="cobalt-stack">
            <CoInput label="Name" name="name" required placeholder="Ada Lovelace" />
            <CoTextarea label="Message" name="message" rows={4} placeholder="Write a message" />
            <div className="cobalt-form-row">
              <CoButton type="submit" variant="primary">
                Submit
              </CoButton>
              <CoButton type="reset" variant="secondary">
                Reset
              </CoButton>
            </div>
          </div>
        </CoForm>
      );
  }
}

function drawer(slot: string | undefined, args: WrapperStoryArgs) {
  const selectedValues = getWrapperStorySelectedValues(args);

  return (
    <CoNavDrawer
      slot={slot}
      {...getWrapperStoryComponentProps('navDrawer', args)}
      {...getWrapperStoryEventProps('navDrawer', args)}
    >
      {getWrapperStoryOptionItems('navDrawer', args).map((item) => (
        <CoNavDrawerItem
          key={item.value}
          value={item.value}
          icon={item.icon ?? 'home'}
          selected={selectedValues.includes(item.value)}
          disabled={item.disabled}
        >
          {item.label}
        </CoNavDrawerItem>
      ))}
      <CoNavSeparator />
      <CoNavDrawerItem value="help" icon="info">
        Help
      </CoNavDrawerItem>
    </CoNavDrawer>
  );
}

function railBar(slot: string | undefined, args: WrapperStoryArgs) {
  const selectedValues = getWrapperStorySelectedValues(args);

  return (
    <CoNavRailBar
      slot={slot}
      {...getWrapperStoryComponentProps('navRailBar', args)}
      {...getWrapperStoryEventProps('navRailBar', args)}
    >
      {getWrapperStoryOptionItems('navRailBar', args).map((item) => (
        <CoNavRailItem
          key={item.value}
          value={item.value}
          icon={item.icon ?? 'home'}
          selected={selectedValues.includes(item.value)}
          disabled={item.disabled}
        >
          {item.label}
        </CoNavRailItem>
      ))}
    </CoNavRailBar>
  );
}

function checkboxChildren(
  componentId: 'checkboxGroup' | 'checkboxIndeterminate',
  args: WrapperStoryArgs,
) {
  const selectedValues = getWrapperStorySelectedValues(args);

  return getWrapperStoryOptionItems(componentId, args).map((item) => (
    <CoCheckbox
      key={item.value}
      value={item.value}
      checked={selectedValues.includes(item.value)}
      disabled={item.disabled}
    >
      {item.label}
    </CoCheckbox>
  ));
}

function radioChildren(componentId: 'radioGroup', args: WrapperStoryArgs) {
  const selectedValues = getWrapperStorySelectedValues(args);

  return getWrapperStoryOptionItems(componentId, args).map((item) => (
    <CoRadio
      key={item.value}
      value={item.value}
      checked={selectedValues.includes(item.value)}
      disabled={item.disabled}
    >
      {item.label}
    </CoRadio>
  ));
}

function optionChildren(componentId: 'combobox' | 'listbox' | 'select', args: WrapperStoryArgs) {
  const selectedValues = getWrapperStorySelectedValues(args);

  return getWrapperStoryOptionItems(componentId, args).map((item) => (
    <CoOption
      key={item.value}
      value={item.value}
      checked={selectedValues.includes(item.value)}
      disabled={item.disabled}
    >
      {item.label}
    </CoOption>
  ));
}

function slotIcon(slot: string, name: string) {
  if (!name) return null;
  return <CoIcon slot={slot} name={name} size="sm" />;
}

function slotText(slot: string, value: string) {
  if (!value) return null;
  return <span slot={slot}>{value}</span>;
}
