// packages/cli/templates/angular/_variants/base/src/app/app.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CoBanner } from '@cobalt/angular/banner';
import { CoButton } from '@cobalt/angular/button';
import { CoCard } from '@cobalt/angular/card';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CoBanner, CoButton, CoCard],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './app.component.html',
})
export class AppComponent {
  handleSuccess() {
    console.log('Success');
  }
}

<main class="starter-page">
  <co-banner label="Cobalt starter banner">
    <span slot="title">Cobalt starter</span>
  </co-banner>
  <section class="starter-content">
    <co-card label="Starter content">
      <div class="starter-card">
        <p class="starter-eyebrow">Angular</p>
        <h1 class="starter-title">Build with Cobalt components</h1>
        <p class="starter-copy">
          Tokens, base styles, theme styles, and Angular directives are ready to use.
        </p>
        <div>
          <co-button variant="success" (coFocus)="handleSuccess()">Success</co-button>
        </div>
      </div>
    </co-card>
  </section>
</main>

// packages/cli/templates/react/_variants/base/src/App.tsx
import { CoBanner } from '@cobalt/react/banner';
import { CoButton } from '@cobalt/react/button';
import { CoCard } from '@cobalt/react/card';

export function App() {
  return (
    <main className="starter-page">
      <CoBanner label="Cobalt starter banner">
        <span slot="title">Cobalt starter</span>
      </CoBanner>
      <section className="starter-content">
        <CoCard label="Starter content">
          <div className="starter-card">
            <p className="starter-eyebrow">React</p>
            <h1 className="starter-title">Build with Cobalt components</h1>
            <p className="starter-copy">
              Tokens, base styles, theme styles, and React wrappers are ready to use.
            </p>
            <div>
              <CoButton variant="success" onCoFocus={() => console.log('Success')}>
                Success
              </CoButton>
            </div>
          </div>
        </CoCard>
      </section>
    </main>
  );
}
