// packages/cli/templates/react/_variants/base/src/App.tsx
import { CoBanner } from '@cobalt/react/banner';
import { CoButton } from '@cobalt/react/button';
import { CoCard } from '@cobalt/react/card';

export function App() {
  return (
    <main className="starter-page">
      <CoBanner label="Cobalt starter banner">
        <span slot="title">Cobalt starter</span>
      </CoBanner>
      <section className="starter-content">
        <CoCard label="Starter content">
          <div className="starter-card">
            <p className="starter-eyebrow">React</p>
            <h1 className="starter-title">Build with Cobalt components</h1>
            <p className="starter-copy">
              Tokens, base styles, theme styles, and React wrappers are ready to use.
            </p>
            <div>
              <CoButton variant="success" onCoFocus={() => console.log('Success')}>
                Success
              </CoButton>
            </div>
          </div>
        </CoCard>
      </section>
    </main>
  );
}

// packages/create-cobalt/templates/vue/_variants/base/src/App.vue
<script setup lang="ts">
import { CoBanner } from '@cobalt/vue/banner';
import { CoButton } from '@cobalt/vue/button';
import { CoCard } from '@cobalt/vue/card';

function handleSuccess() {
  console.log('Success');
}
</script>

<template>
  <main class="starter-page">
    <CoBanner label="Cobalt starter banner">
      <span slot="title">Cobalt starter</span>
    </CoBanner>
    <section class="starter-content">
      <CoCard label="Starter content">
        <div class="starter-card">
          <p class="starter-eyebrow">Vue</p>
          <h1 class="starter-title">Build with Cobalt components</h1>
          <p class="starter-copy">
            Tokens, base styles, theme styles, and Vue wrappers are ready to use.
          </p>
          <div>
            <CoButton variant="success" @co-focus="handleSuccess">Success</CoButton>
          </div>
        </div>
      </CoCard>
    </section>
  </main>
</template>
